name: Deploy to GoDaddy via FTP

on:
  push:
    branches:
      - main # Change this to your default branch if it's not 'main'

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: ⚙️ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './noor-al-reef/package-lock.json'
        
    - name: 📦 Install Dependencies
      run: npm ci
      working-directory: ./noor-al-reef
      
    - name: 🛠️ Build Project
      run: npm run build
      working-directory: ./noor-al-reef
      
    - name: 📂 Sync files to GoDaddy FTP Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./noor-al-reef/dist/
        server-dir: /public_html/
